### ISSUE TITLE
Custom minidsp descriptor creates exception

### ISSUE THREAD

**Issue by mohitarora24** [3ll3d00d/ezbeq#63]
I was trying to create a custom miniDSP descriptor on the same lines as 2x4HD just trying to enable 1st Input and disable 2nd i.e. want to just apply BEQ to first input.

So I made a descriptor like:
```
    descriptor:
      name: 2x4HD
      fs: 96000
      routes:
      - name: input
        biquads: 10
        channels: [0]
        slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      - name: crossover
        biquads: 4
        channels: [0, 1, 2, 3]
        slots: []
        groups: [0, 1]
      - name: output
        biquads: 10
        channels: [0, 1, 2, 3]
        slots: []
```

i.e. `input` has just 1 channel `[0]`

Now when trying to apply a BEQ filter it returns failure as there is an exception in `BeqFilterAllocator()` API.

It seems to crash because `r.beq_slots` is `None` and not `[]`. Input in the config is `[]` in both `crossover` and `output` but it seems in `make_peq_layout()` API it converts these `[]` to `None` in that `to_ints()` func.

Would be nice if this is fixed.
