### ISSUE TITLE
Feature request: Support for Camilladsp 3.0.0 config format 

### ISSUE THREAD

**Issue by mike811** [3ll3d00d/ezbeq#77]
Hey,

I did some tests with CDSP 3.0.0 beta and noticed that the configuration file format changed and ezbeq throws therefore errors: "SetConfig failed : Error"

Looking at the differences I noticed that pipeline section of 3.0.0 has "channels" and not "channel" and numbers are now with a preceding "-".

Would be great if both formats could be supported.

Regards 
Michael

**Comment by 3ll3d00d** [comment]
would be even better if config format only changed for meaningful reasons :)

post back when 3.0 is final and I'll look at it, not doing anything til then

**Comment by mike811** [comment]
3.0.0 beta (or next30) offers to apply same filters to multiple channels. Therefore the config format changed.
Apparently two versions work here when I tested it. Square brackets and also "- number":

```
pipeline:
- bypassed: null
  channels: []
  description: bla
  names:
  - test
  type: Filter
- bypassed: null
  description: mixi
  name: testing
  type: Mixer
- bypassed: null
  channels: [8, 9]
  description: blub
  names:
  - test
  type: Filter
processors: null
title: 18i20 CamillaDSP 3.0
```

```
pipeline:
- bypassed: null
  channels: []
  description: bla
  names:
  - test
  type: Filter
- bypassed: null
  description: mixi
  name: testing
  type: Mixer
- bypassed: null
  channels:
  - 8
  - 9
  description: blub
  names:
  - test
  type: Filter
processors: null
title: 18i20 CamillaDSP 3.0

```
