### ISSUE TITLE
Filter position in Camilladsp config with multiple mixer stages

### ISSUE THREAD

**Issue by mike811** [3ll3d00d/ezbeq#83]
Camilladsp config may have multiple mixers as displayed below (here named "Input" and "Bass management 1") 

```
mixers:
  Input:
    channels:
      in: 20
      out: 12
    description: null
    labels:
    - NOP
    - HOL
    - NUP
    - XYZ
.
.
.
  Bass management 1:
    channels:
      in: 12
      out: 24
    description: null
    labels:
    - TRR
    - TRL
    - TFL
.
.
.
``` 
Could beq filters be applied to the first mixer stage after the keyword "mixers:"?
Alternatively and more flexible: Parsing of "description" field. Here users could put "BEQ filter location" or similar to specify at which mixer stage they want BEQs to be applied.
